---
- name: Create /etc/docker directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: "0755"

- name: Deploy Docker daemon config
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: "0644"
    validate: "dockerd --validate --config-file %s"
  notify: Restart docker

- name: Enable and set Docker service state
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
